language: node_js
node_js:
  - 'stable'
cache: npm
 install: 
 - npm ci
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
